name: Build, test (& deploy) worker

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.7  '
      - name: Install worker
        run: sudo pip install .
      - name: Install webdriver
        run: sudo apt-get install chromium-chromedriver
      - name: Run worker tests
        run: dualis-scanner-worker ${{ secrets.DUALIS_UNAME }} ${{ secrets.DUALIS_PWD }} --driver=/usr/bin/chromedriver -v --dry
  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy worker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: cd dualis-scanner.worker && git pull && pip install . --upgrade --force-reinstall --no-warn-script-location